version: '3.8'

services:
  service_a:
    build: ./app
    volumes:
      - ./logs:/app/logs
      - ./error_reports:/app/error_reports
    command: python service_1.py
    depends_on:
      - service_2

  service_b:
    build: ./app
    ports:
      - "5001:5001"
    volumes:
      - ./logs:/app/logs
      - ./error_reports:/app/error_reports
